name: rx_widget_demo
description: Rx Widgets Example
environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  rxdart : any
  json_annotation: any
  http: ^0.13.1
  rx_command: ^6.0.0
  rx_widgets: 
    path: ../
 
dev_dependencies: 
  test: any
  mockito: ^5.3.2
  quiver: any
  build_runner: any
  json_serializable: ^6.5.3
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  fonts:
   - family:  WeatherIcons
     fonts:
      - asset: fonts/WeatherIcons.ttf