name: rx_widgets
description: A package with stream based Flutter Widgets that facilitate an reactive programming style.
version: 4.1.0
homepage: https://github.com/escamoteur/rx_widgets
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
 flutter:
    sdk: flutter

 rx_command: ^6.0.0

dev_dependencies:
  flutter_test: 
    sdk: flutter 

flutter: